#spring
spring:
  data:
    mongodb:
      uri: mongodb+srv://saeyoung:dkstpdud13@cluster0.d12ow.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false
  thymeleaf:
    cache: false

server:
  port: 8089
